services:
  app:
    image: bender/app:latest
    restart: always
    build:
      context: .
      args:
        EXPO_PUBLIC_HOST_URL: ${EXPO_PUBLIC_HOST_URL}
    depends_on:
      - database
    ports:
      - ${PORT:-3000}:3000
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

  database:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - database:/var/lib/postgresql/data

  backup:
    image: offen/docker-volume-backup:v2
    restart: always
    depends_on:
      - database
    environment:
      BACKUP_LATEST_SYMLINK: backup-latest.tar.gz
      BACKUP_CRON_EXPRESSION: 0 0 * * *
      BACKUP_RETENTION_DAYS: 14
    volumes:
      - database:/backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DATABASE_BACKUP_PATH}/${COMPOSE_PROJECT_NAME}:/archive
    profiles:
      - production

volumes:
  database:
