services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    healthcheck:
      test: pg_isready
      interval: 3s
      timeout: 1s
      retries: 3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGDATABASE: ${POSTGRES_DB}
      PGPORT: ${POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    labels:
      - docker-volume-backup.archive-pre=/bin/sh -c 'mkdir -p /var/lib/postgresql/data/backup && pg_dump > /var/lib/postgresql/data/backup/dump.sql'

  backup:
    image: offen/docker-volume-backup:v2
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      BACKUP_LATEST_SYMLINK: backup-latest.tar.gz
      BACKUP_CRON_EXPRESSION: 0 0 * * *
      BACKUP_RETENTION_DAYS: 14
      BACKUP_SOURCES: /postgres/backup
      EXEC_FORWARD_OUTPUT: true
    volumes:
      - postgres:/postgres:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${POSTGRES_BACKUP_PATH}/${COMPOSE_PROJECT_NAME}:/archive

  app:
    image: bender/app:latest
    restart: unless-stopped
    build:
      context: .
      args:
        EXPO_PUBLIC_HOST_URL: ${EXPO_PUBLIC_HOST_URL}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

volumes:
  postgres:
